# SmartCityX - Dev Profile using Neon Postgres
spring.datasource.url=jdbc:postgresql://ep-still-forest-atigo975-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Xzm8YwTaoGu7
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
